name: Playwright Test Runner

on:
  schedule:
    - cron: "0/10 * * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILDKITE_ANALYTICS_TOKEN: ${{ secrets.BUILDKITE_ANALYTICS_TOKEN }}
  CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
  CURRENTS_CI_BUILD_ID: "${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt }}"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests
      run: npx playwright test

